In [45]:
import numpy as np

In [46]:
N= 100
D = 2

In [47]:
X = np.random.rand(N,D)

In [48]:
print(X)
print(X.shape)

[[0.71495027 0.57260759]
 [0.89145006 0.31735329]
 [0.65069283 0.37362717]
 [0.8557428  0.11329269]
 [0.62939203 0.07147856]
 [0.43381658 0.56920965]
 [0.62436442 0.54338237]
 [0.05928443 0.76534119]
 [0.91358229 0.76754985]
 [0.46519742 0.85148827]
 [0.1803761  0.57246106]
 [0.40901283 0.60062281]
 [0.63393765 0.95857517]
 [0.3592355  0.5615166 ]
 [0.87753898 0.02038436]
 [0.21045216 0.04618662]
 [0.08793784 0.64244576]
 [0.95446652 0.88731416]
 [0.22133074 0.41710592]
 [0.78609556 0.25763535]
 [0.82895574 0.13056896]
 [0.14495079 0.53491273]
 [0.69284371 0.9209848 ]
 [0.40390127 0.09415586]
 [0.3027403  0.31102991]
 [0.76159247 0.08157626]
 [0.4023978  0.99395342]
 [0.41735915 0.82871405]
 [0.59590379 0.35535443]
 [0.11282884 0.71686443]
 [0.1385311  0.91446942]
 [0.53964034 0.09508165]
 [0.2665146  0.26456403]
 [0.5654645  0.34132405]
 [0.20691127 0.27180613]
 [0.06216655 0.25073252]
 [0.14334229 0.5122604 ]
 [0.81235937 0.8644455 ]
 [0.561105   0.46498953]
 [0.3361203  0.46519845]


In [49]:
#first we need to find error

#So iam going to send my first 50 points

X[:50,:]

array([[0.71495027, 0.57260759],
       [0.89145006, 0.31735329],
       [0.65069283, 0.37362717],
       [0.8557428 , 0.11329269],
       [0.62939203, 0.07147856],
       [0.43381658, 0.56920965],
       [0.62436442, 0.54338237],
       [0.05928443, 0.76534119],
       [0.91358229, 0.76754985],
       [0.46519742, 0.85148827],
       [0.1803761 , 0.57246106],
       [0.40901283, 0.60062281],
       [0.63393765, 0.95857517],
       [0.3592355 , 0.5615166 ],
       [0.87753898, 0.02038436],
       [0.21045216, 0.04618662],
       [0.08793784, 0.64244576],
       [0.95446652, 0.88731416],
       [0.22133074, 0.41710592],
       [0.78609556, 0.25763535],
       [0.82895574, 0.13056896],
       [0.14495079, 0.53491273],
       [0.69284371, 0.9209848 ],
       [0.40390127, 0.09415586],
       [0.3027403 , 0.31102991],
       [0.76159247, 0.08157626],
       [0.4023978 , 0.99395342],
       [0.41735915, 0.82871405],
       [0.59590379, 0.35535443],
       [0.11282884, 0.71686443],
       [0.

In [50]:
X[50:, :]

array([[0.27494077, 0.64270972],
       [0.23989885, 0.46481613],
       [0.5861127 , 0.16240817],
       [0.65493951, 0.93082252],
       [0.67523483, 0.83256588],
       [0.76050348, 0.00335513],
       [0.93886164, 0.93130648],
       [0.14306652, 0.86457889],
       [0.46865623, 0.9500797 ],
       [0.46678652, 0.54741633],
       [0.80076163, 0.979929  ],
       [0.57604277, 0.25515842],
       [0.02761797, 0.68933842],
       [0.2597241 , 0.8570875 ],
       [0.70065241, 0.12841622],
       [0.68597866, 0.1284464 ],
       [0.52573253, 0.1969384 ],
       [0.58564126, 0.68340296],
       [0.40419989, 0.60541646],
       [0.13360616, 0.09171242],
       [0.49968117, 0.38843624],
       [0.84493111, 0.43057495],
       [0.73021491, 0.15271338],
       [0.02271393, 0.13302752],
       [0.38239879, 0.16403123],
       [0.86257686, 0.6749887 ],
       [0.16515257, 0.51423844],
       [0.22701448, 0.46583495],
       [0.20186283, 0.72811806],
       [0.78864363, 0.68784779],
       [0.

In [51]:
2*np.ones((50,D))

array([[2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.]])

In [52]:
#first 50 rows are subtracted that by negative 2
#center the first 50 points at(-2,-2)
X[:50, :] = X[:50, :]-2*np.ones((50, D))

In [53]:
X[:50, :]

array([[-1.28504973, -1.42739241],
       [-1.10854994, -1.68264671],
       [-1.34930717, -1.62637283],
       [-1.1442572 , -1.88670731],
       [-1.37060797, -1.92852144],
       [-1.56618342, -1.43079035],
       [-1.37563558, -1.45661763],
       [-1.94071557, -1.23465881],
       [-1.08641771, -1.23245015],
       [-1.53480258, -1.14851173],
       [-1.8196239 , -1.42753894],
       [-1.59098717, -1.39937719],
       [-1.36606235, -1.04142483],
       [-1.6407645 , -1.4384834 ],
       [-1.12246102, -1.97961564],
       [-1.78954784, -1.95381338],
       [-1.91206216, -1.35755424],
       [-1.04553348, -1.11268584],
       [-1.77866926, -1.58289408],
       [-1.21390444, -1.74236465],
       [-1.17104426, -1.86943104],
       [-1.85504921, -1.46508727],
       [-1.30715629, -1.0790152 ],
       [-1.59609873, -1.90584414],
       [-1.6972597 , -1.68897009],
       [-1.23840753, -1.91842374],
       [-1.5976022 , -1.00604658],
       [-1.58264085, -1.17128595],
       [-1.40409621,

In [54]:
#last 50 rows are added with positive 2 values
#last 50 points at(2,2)
X[50:, :] = X[50:, :]+2*np.ones((50, D))

In [55]:
X[50:, :]

array([[2.27494077, 2.64270972],
       [2.23989885, 2.46481613],
       [2.5861127 , 2.16240817],
       [2.65493951, 2.93082252],
       [2.67523483, 2.83256588],
       [2.76050348, 2.00335513],
       [2.93886164, 2.93130648],
       [2.14306652, 2.86457889],
       [2.46865623, 2.9500797 ],
       [2.46678652, 2.54741633],
       [2.80076163, 2.979929  ],
       [2.57604277, 2.25515842],
       [2.02761797, 2.68933842],
       [2.2597241 , 2.8570875 ],
       [2.70065241, 2.12841622],
       [2.68597866, 2.1284464 ],
       [2.52573253, 2.1969384 ],
       [2.58564126, 2.68340296],
       [2.40419989, 2.60541646],
       [2.13360616, 2.09171242],
       [2.49968117, 2.38843624],
       [2.84493111, 2.43057495],
       [2.73021491, 2.15271338],
       [2.02271393, 2.13302752],
       [2.38239879, 2.16403123],
       [2.86257686, 2.6749887 ],
       [2.16515257, 2.51423844],
       [2.22701448, 2.46583495],
       [2.20186283, 2.72811806],
       [2.78864363, 2.68784779],
       [2.

In [56]:
#we have to set first 50 rows are 0's and last 50 rows are 1's
#label the first 50 are 0's and last 50 are 1's
T = np.array([0]*50 + [1]*50)
T

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [57]:
#we have to creat bias terms
#add a column of ones
ones = np.array([[1]*N]).T
ones

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [58]:
#we have to concatenate the X values and bias values
Xb = np.concatenate((ones, X), axis = 1)
Xb

array([[ 1.        , -1.28504973, -1.42739241],
       [ 1.        , -1.10854994, -1.68264671],
       [ 1.        , -1.34930717, -1.62637283],
       [ 1.        , -1.1442572 , -1.88670731],
       [ 1.        , -1.37060797, -1.92852144],
       [ 1.        , -1.56618342, -1.43079035],
       [ 1.        , -1.37563558, -1.45661763],
       [ 1.        , -1.94071557, -1.23465881],
       [ 1.        , -1.08641771, -1.23245015],
       [ 1.        , -1.53480258, -1.14851173],
       [ 1.        , -1.8196239 , -1.42753894],
       [ 1.        , -1.59098717, -1.39937719],
       [ 1.        , -1.36606235, -1.04142483],
       [ 1.        , -1.6407645 , -1.4384834 ],
       [ 1.        , -1.12246102, -1.97961564],
       [ 1.        , -1.78954784, -1.95381338],
       [ 1.        , -1.91206216, -1.35755424],
       [ 1.        , -1.04553348, -1.11268584],
       [ 1.        , -1.77866926, -1.58289408],
       [ 1.        , -1.21390444, -1.74236465],
       [ 1.        , -1.17104426, -1.869

In [60]:
#we have to calculate the weights
#randomly initilize the weights
w = np.random.rand(D + 1)
w

array([0.19867032, 0.2973189 , 0.25193176])

In [61]:
#calculate the prediction output
z = np.dot(Xb,w)
z

array([-0.54300474, -0.55483468, -0.61223918, -0.61686047, -0.69469314,
       -0.62744715, -0.57730039, -0.68939087, -0.43483554, -0.54700208,
       -0.70198066, -0.6269078 , -0.46985383, -0.65155964, -0.63378661,
       -0.82562373, -0.71183294, -0.39250745, -0.72894297, -0.60120341,
       -0.62047233, -0.72197289, -0.46181015, -0.75602267, -0.73146228,
       -0.65284352, -0.5297821 , -0.56696285, -0.63313248, -0.68568394,
       -0.6282592 , -0.71543165, -0.7539391 , -0.64571736, -0.76983578,
       -0.81818023, -0.72815797, -0.44051994, -0.61585826, -0.68269783,
       -0.4942551 , -0.43148519, -0.52742751, -0.75807402, -0.53701729,
       -0.51519234, -0.61901136, -0.62649153, -0.4410353 , -0.57395047,
        1.54083573,  1.48560006,  1.51234981,  1.72640131,  1.70768152,
        1.52412898,  1.81093865,  1.55752292,  1.67586726,  1.57386767,
        1.78212846,  1.53272257,  1.47904924,  1.5903201 ,  1.53784098,
        1.53348581,  1.50309691,  1.64346478,  1.56987156,  1.36

In [63]:
#another method
z= Xb.dot(w)
z

array([-0.54300474, -0.55483468, -0.61223918, -0.61686047, -0.69469314,
       -0.62744715, -0.57730039, -0.68939087, -0.43483554, -0.54700208,
       -0.70198066, -0.6269078 , -0.46985383, -0.65155964, -0.63378661,
       -0.82562373, -0.71183294, -0.39250745, -0.72894297, -0.60120341,
       -0.62047233, -0.72197289, -0.46181015, -0.75602267, -0.73146228,
       -0.65284352, -0.5297821 , -0.56696285, -0.63313248, -0.68568394,
       -0.6282592 , -0.71543165, -0.7539391 , -0.64571736, -0.76983578,
       -0.81818023, -0.72815797, -0.44051994, -0.61585826, -0.68269783,
       -0.4942551 , -0.43148519, -0.52742751, -0.75807402, -0.53701729,
       -0.51519234, -0.61901136, -0.62649153, -0.4410353 , -0.57395047,
        1.54083573,  1.48560006,  1.51234981,  1.72640131,  1.70768152,
        1.52412898,  1.81093865,  1.55752292,  1.67586726,  1.57386767,
        1.78212846,  1.53272257,  1.47904924,  1.5903201 ,  1.53784098,
        1.53348581,  1.50309691,  1.64346478,  1.56987156,  1.36

In [64]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [65]:
Y = sigmoid(z)
Y

array([0.36748888, 0.36474345, 0.35154858, 0.35049582, 0.33298988,
       0.34808961, 0.35955401, 0.33416859, 0.39297224, 0.36656023,
       0.33137324, 0.34821202, 0.38465084, 0.34263816, 0.34665243,
       0.3045712 , 0.32919396, 0.40311383, 0.32542673, 0.35406842,
       0.34967403, 0.32695869, 0.38655649, 0.31951041, 0.32487392,
       0.34234904, 0.37056771, 0.36193793, 0.3468006 , 0.33499389,
       0.34790536, 0.32839976, 0.3199636 , 0.34395527, 0.31651463,
       0.30615008, 0.32559908, 0.39161709, 0.35072401, 0.33565944,
       0.37889169, 0.39377174, 0.37111708, 0.31906456, 0.36888171,
       0.37397711, 0.35000633, 0.3483065 , 0.39149431, 0.36032577,
       0.82358618, 0.81541695, 0.81940919, 0.84895153, 0.84653533,
       0.82114569, 0.85947528, 0.82599762, 0.84235651, 0.82833428,
       0.85595949, 0.82240431, 0.81442893, 0.83066113, 0.82315065,
       0.82251576, 0.81803591, 0.83800584, 0.8277653 , 0.79575979,
       0.82398683, 0.8398162 , 0.82531081, 0.79206844, 0.81033

In [66]:
#calculate the cross entropy error
#So we can take in the target and the predicted output 
def cross_entropy(T, Y):
    E = 0
    for i in range(N):
        if T[i] == 1:  # here target value is 1
           E -= np.log(Y) #here subtract log Y
        else:       #here target value is 0
           E -= np.log(1 - Y[i])
    return E


In [70]:
print(cross_entropy(T, Y))

[71.66549479 72.04043566 73.88275231 74.03270825 76.59454358 74.37714999
 72.7569276  76.41786652 68.31319888 71.79200582 76.83788079 74.35957117
 69.38334707 75.16639928 74.58401589 81.05490282 77.16779253 67.03919896
 77.74328115 73.52563919 74.15007824 77.50845675 69.13624663 78.66065526
 77.82828913 75.20860732 71.2483387  72.42651179 74.56264943 76.29453347
 74.403623   77.28856584 78.58978635 74.97456692 79.13167433 80.79637545
 77.71680766 68.48592078 74.0001667  76.19529385 70.13762868 68.21157793
 71.17426808 78.73047412 71.47634686 70.79041798 74.10258516 74.34600635
 68.50159917 72.64972024 31.31673787 31.81516909 31.57096892 29.80004318
 29.94255124 31.46512048 29.18404463 31.17055319 30.189981   31.02930841
 29.38899536 31.38854109 31.87578935 30.88905126 31.34318622 31.38176584
 31.65483576 30.44889438 31.06366499 33.03527946 31.29242038 30.34099493
 31.21214525 33.26775797 32.12773857 29.82059556 31.90572046 31.84820307
 31.31859372 29.9636042  30.30963662 31.45477095 31

In [71]:
#here weights depends only on the means
#here zero is the bias term and 4 is weights
w = np.array([0, 4, 4])

z = Xb.dot(w)
z

array([-10.84976856, -11.1647866 , -11.90271998, -12.12385807,
       -13.19651762, -11.98789511, -11.32901284, -12.70149753,
        -9.27547146, -10.73325725, -12.98865137, -11.96145742,
        -9.62994871, -12.31699159, -12.40830662, -14.97344487,
       -13.07846561,  -8.63287725, -13.44625334, -11.82507635,
       -12.1619012 , -13.28054592,  -9.54468594, -14.00777147,
       -13.54491915, -12.62732506, -10.41459515, -11.01570719,
       -12.19496708, -12.68122693, -11.78799795, -13.46111201,
       -13.87568551, -12.3728458 , -14.08513038, -14.7484037 ,
       -13.37758921,  -9.29278053, -11.89562189, -12.79472503,
       -10.01594556,  -9.2653547 , -10.38149209, -13.8465903 ,
       -10.7698798 , -10.32806875, -11.67603295, -12.30627041,
        -9.30608313, -11.42016654,  19.67060196,  18.81885995,
        18.99408346,  22.34304813,  22.03120286,  19.05543446,
        23.4806725 ,  20.03058165,  21.67494373,  20.0568114 ,
        23.12276254,  19.32480478,  18.86782555,  20.46

In [72]:
Y = sigmoid(z)
Y

array([1.94087228e-05, 1.41640887e-05, 6.77191426e-06, 5.42841425e-06,
       1.85705349e-06, 6.21900067e-06, 1.20189635e-05, 3.04655054e-06,
       9.36856851e-05, 2.18070105e-05, 2.28612193e-06, 6.38560829e-06,
       6.57261009e-05, 4.47503642e-06, 4.08450216e-06, 3.14134316e-07,
       2.08974670e-06, 1.78119589e-04, 1.44665757e-06, 7.31865737e-06,
       5.22578032e-06, 1.70738494e-06, 7.15755149e-05, 8.25090883e-07,
       1.31073768e-06, 3.28111142e-06, 2.99906424e-05, 1.64411432e-05,
       5.05581173e-06, 3.10893592e-06, 7.59511303e-06, 1.42532110e-06,
       9.41598894e-07, 4.23194005e-06, 7.63669188e-07, 3.93413706e-07,
       1.54948063e-06, 9.20781747e-05, 6.82015261e-06, 2.77536634e-06,
       4.46797471e-05, 9.46382014e-05, 3.10000082e-05, 9.69397326e-07,
       2.10228457e-05, 3.27011127e-05, 8.49492659e-06, 4.52327198e-06,
       9.08615174e-05, 1.09718516e-05, 9.99999997e-01, 9.99999993e-01,
       9.99999994e-01, 1.00000000e+00, 1.00000000e+00, 9.99999995e-01,
      

In [73]:
print(cross_entropy(T, Y))

[5.42490452e+02 5.58241092e+02 5.95137391e+02 6.06194229e+02
 6.59827027e+02 5.99396120e+02 5.66452297e+02 6.35076082e+02
 4.63779311e+02 5.36665007e+02 6.49433736e+02 5.98074244e+02
 4.81501776e+02 6.15850857e+02 6.20416589e+02 7.48673313e+02
 6.53924438e+02 4.31653823e+02 6.72313793e+02 5.91255237e+02
 6.08096375e+02 6.64028435e+02 4.77238929e+02 7.00389668e+02
 6.77247077e+02 6.31367471e+02 5.20732311e+02 5.50787235e+02
 6.09749661e+02 6.34062555e+02 5.89401331e+02 6.73056726e+02
 6.93785376e+02 6.18643555e+02 7.04257611e+02 7.37421258e+02
 6.68880592e+02 4.64644684e+02 5.94782489e+02 6.39737444e+02
 5.00800566e+02 4.63273521e+02 5.19077208e+02 6.92330617e+02
 5.38496095e+02 5.16406126e+02 5.83803126e+02 6.15314800e+02
 4.65309754e+02 5.71009929e+02 1.05379767e-03 1.05399018e-03
 1.05393621e-03 1.05366431e-03 1.05366793e-03 1.05391944e-03
 1.05365758e-03 1.05375436e-03 1.05367371e-03 1.05375178e-03
 1.05365895e-03 1.05385686e-03 1.05397414e-03 1.05371900e-03
 1.05385859e-03 1.053870