In [26]:
import numpy as np

In [27]:
N = 100
D = 2

In [28]:
X = np.random.randn(N,D)
print(X)

[[ 3.25644299e-02  1.18141100e+00]
 [-1.15684205e+00  3.89965129e-01]
 [-6.29645451e-01 -5.82151992e-01]
 [ 6.39036307e-01 -1.29458910e+00]
 [ 1.40962114e+00  1.37908154e-01]
 [ 7.73947727e-01 -8.91019077e-01]
 [-1.04347846e+00  1.13629393e-01]
 [-9.39448104e-01 -6.46370513e-01]
 [-2.52801563e-01  2.17043411e-01]
 [-4.54563100e-04  2.68390477e-01]
 [-1.12663564e-02  1.27194093e+00]
 [ 3.08044772e-01 -1.72415118e-01]
 [-8.62706117e-01 -2.42219792e+00]
 [ 5.42245839e-01  1.46946008e+00]
 [ 1.08474307e+00  1.47349042e+00]
 [ 8.21989629e-01  1.21990970e+00]
 [-5.82517600e-01 -1.42140209e-01]
 [ 1.46518120e+00 -2.62260619e-02]
 [ 6.01856318e-01 -1.08836266e+00]
 [-6.42381267e-01 -1.05470892e+00]
 [ 1.02010727e+00 -5.96046068e-01]
 [-1.48480172e+00 -7.88480966e-01]
 [-8.01005330e-01  8.83543888e-01]
 [ 5.00730024e-01  8.75387500e-01]
 [-1.21792554e+00  3.16075257e-01]
 [-1.38299933e+00  3.71790593e-01]
 [-3.52855854e-02  1.31431176e+00]
 [ 4.90369186e-01  1.07853774e+00]
 [ 1.00394237e+00  1

In [29]:
X[:50, :] = X[:50, :] - 2*np.ones((50,D))
X

array([[-1.96743557e+00, -8.18589001e-01],
       [-3.15684205e+00, -1.61003487e+00],
       [-2.62964545e+00, -2.58215199e+00],
       [-1.36096369e+00, -3.29458910e+00],
       [-5.90378861e-01, -1.86209185e+00],
       [-1.22605227e+00, -2.89101908e+00],
       [-3.04347846e+00, -1.88637061e+00],
       [-2.93944810e+00, -2.64637051e+00],
       [-2.25280156e+00, -1.78295659e+00],
       [-2.00045456e+00, -1.73160952e+00],
       [-2.01126636e+00, -7.28059071e-01],
       [-1.69195523e+00, -2.17241512e+00],
       [-2.86270612e+00, -4.42219792e+00],
       [-1.45775416e+00, -5.30539916e-01],
       [-9.15256930e-01, -5.26509583e-01],
       [-1.17801037e+00, -7.80090303e-01],
       [-2.58251760e+00, -2.14214021e+00],
       [-5.34818798e-01, -2.02622606e+00],
       [-1.39814368e+00, -3.08836266e+00],
       [-2.64238127e+00, -3.05470892e+00],
       [-9.79892732e-01, -2.59604607e+00],
       [-3.48480172e+00, -2.78848097e+00],
       [-2.80100533e+00, -1.11645611e+00],
       [-1.

In [30]:
X[50:,:] = X[50:, :] + 2*np.ones((50, D))
X

array([[-1.96743557, -0.818589  ],
       [-3.15684205, -1.61003487],
       [-2.62964545, -2.58215199],
       [-1.36096369, -3.2945891 ],
       [-0.59037886, -1.86209185],
       [-1.22605227, -2.89101908],
       [-3.04347846, -1.88637061],
       [-2.9394481 , -2.64637051],
       [-2.25280156, -1.78295659],
       [-2.00045456, -1.73160952],
       [-2.01126636, -0.72805907],
       [-1.69195523, -2.17241512],
       [-2.86270612, -4.42219792],
       [-1.45775416, -0.53053992],
       [-0.91525693, -0.52650958],
       [-1.17801037, -0.7800903 ],
       [-2.5825176 , -2.14214021],
       [-0.5348188 , -2.02622606],
       [-1.39814368, -3.08836266],
       [-2.64238127, -3.05470892],
       [-0.97989273, -2.59604607],
       [-3.48480172, -2.78848097],
       [-2.80100533, -1.11645611],
       [-1.49926998, -1.1246125 ],
       [-3.21792554, -1.68392474],
       [-3.38299933, -1.62820941],
       [-2.03528559, -0.68568824],
       [-1.50963081, -0.92146226],
       [-0.99605763,

In [31]:
T = np.array([0]*50 + [1]*50)
print(T)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [32]:
ones = np.ones((N, 1))
ones

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [33]:
Xb = np.concatenate((X, ones), axis = 1)
Xb

array([[-1.96743557, -0.818589  ,  1.        ],
       [-3.15684205, -1.61003487,  1.        ],
       [-2.62964545, -2.58215199,  1.        ],
       [-1.36096369, -3.2945891 ,  1.        ],
       [-0.59037886, -1.86209185,  1.        ],
       [-1.22605227, -2.89101908,  1.        ],
       [-3.04347846, -1.88637061,  1.        ],
       [-2.9394481 , -2.64637051,  1.        ],
       [-2.25280156, -1.78295659,  1.        ],
       [-2.00045456, -1.73160952,  1.        ],
       [-2.01126636, -0.72805907,  1.        ],
       [-1.69195523, -2.17241512,  1.        ],
       [-2.86270612, -4.42219792,  1.        ],
       [-1.45775416, -0.53053992,  1.        ],
       [-0.91525693, -0.52650958,  1.        ],
       [-1.17801037, -0.7800903 ,  1.        ],
       [-2.5825176 , -2.14214021,  1.        ],
       [-0.5348188 , -2.02622606,  1.        ],
       [-1.39814368, -3.08836266,  1.        ],
       [-2.64238127, -3.05470892,  1.        ],
       [-0.97989273, -2.59604607,  1.   

In [34]:
w = np.random.randn(D + 1)
w

array([0.31290956, 0.76823044, 1.09172937])

In [35]:
z = Xb.dot(w)
z

array([-0.15276501, -1.13295448, -1.71479959, -1.86513283, -0.52352147,
       -1.51288297, -1.30977145, -1.86107443, -0.9829153 , -0.86450713,
       -0.09693224, -1.10661502, -3.2013058 ,  0.22800725,  0.40085604,
        0.12382955, -1.36202239, -0.63222909, -1.71833737, -2.08181737,
       -1.20925006, -2.14089436, -0.64242754, -0.2413681 , -1.20883254,
       -1.21768349, -0.07189752, -0.0885439 ,  0.29706749, -0.43909435,
       -2.8052841 ,  0.71074057, -1.96201286, -2.47815187,  0.70539544,
       -2.08618723, -1.9486694 , -1.59410396, -1.6984562 , -0.34745378,
       -1.33775015, -0.53614144, -0.44580284, -1.53727615, -0.79598678,
       -1.18351048, -1.09850407, -1.53603666, -2.52648801, -4.25222979,
        2.26290043,  3.62233875,  2.14485544,  3.96788829,  3.16396908,
        4.0777728 ,  3.62249001,  3.7785891 ,  3.91317781,  3.61379204,
        4.03497538,  3.01603574,  4.36880175,  3.88470721,  2.71911064,
        2.99316016,  2.76436414,  3.85949751,  2.99556233,  3.36

In [36]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [37]:
Y = sigmoid(z)
Y

array([0.46188285, 0.24361627, 0.15254222, 0.1341059 , 0.37202917,
       0.18051193, 0.21252509, 0.13457787, 0.27231371, 0.29639854,
       0.4757859 , 0.24850249, 0.03911661, 0.55675614, 0.59889331,
       0.53091789, 0.20391181, 0.34700527, 0.15208544, 0.11087668,
       0.22983377, 0.10518518, 0.344698  , 0.43994923, 0.22990769,
       0.22834437, 0.48203336, 0.47787847, 0.57372549, 0.39195679,
       0.0570393 , 0.67056478, 0.12324937, 0.07740408, 0.66938292,
       0.11044662, 0.12469852, 0.16880728, 0.154667  , 0.41400001,
       0.20788029, 0.36908564, 0.39035914, 0.17693159, 0.31088464,
       0.23442159, 0.25002029, 0.17711217, 0.07402201, 0.01403274,
       0.90575751, 0.97397527, 0.89518706, 0.98143774, 0.95945563,
       0.98333719, 0.97397911, 0.97765576, 0.98041434, 0.97375775,
       0.98262125, 0.95329333, 0.98749202, 0.97986011, 0.93814495,
       0.95226417, 0.94071948, 0.97935655, 0.95237324, 0.96646167,
       0.96367348, 0.94906062, 0.94522558, 0.9817673 , 0.84503

In [38]:
def cross_entropy(T, Y):
    E = 0
    for i in range(N):
        if T[i] == 1:
            E -= np.log(Y[i])
        else:
            E -= np.log(1-Y[i])
    return E

In [39]:
cross_entropy(T, Y)

20.634993876303383

In [40]:
G = T - Y
G

array([-0.46188285, -0.24361627, -0.15254222, -0.1341059 , -0.37202917,
       -0.18051193, -0.21252509, -0.13457787, -0.27231371, -0.29639854,
       -0.4757859 , -0.24850249, -0.03911661, -0.55675614, -0.59889331,
       -0.53091789, -0.20391181, -0.34700527, -0.15208544, -0.11087668,
       -0.22983377, -0.10518518, -0.344698  , -0.43994923, -0.22990769,
       -0.22834437, -0.48203336, -0.47787847, -0.57372549, -0.39195679,
       -0.0570393 , -0.67056478, -0.12324937, -0.07740408, -0.66938292,
       -0.11044662, -0.12469852, -0.16880728, -0.154667  , -0.41400001,
       -0.20788029, -0.36908564, -0.39035914, -0.17693159, -0.31088464,
       -0.23442159, -0.25002029, -0.17711217, -0.07402201, -0.01403274,
        0.09424249,  0.02602473,  0.10481294,  0.01856226,  0.04054437,
        0.01666281,  0.02602089,  0.02234424,  0.01958566,  0.02624225,
        0.01737875,  0.04670667,  0.01250798,  0.02013989,  0.06185505,
        0.04773583,  0.05928052,  0.02064345,  0.04762676,  0.03

In [41]:
learning_rate = 0.1

In [42]:
for i in range(100):
    if i % 10 == 0:
        print(cross_entropy(T,Y))
    # gradient descent formula    
    w = w+learning_rate*(np.dot(Xb.T,T-Y)- 0.1*w)    
    
    #recalculating sigmoid
    z = np.dot(Xb,w)
    #print(z)
    sigmoid = 1/(1+np.exp(-z))
    Y = sigmoid
    #Y

20.634993876303383
0.4129553186031287
0.4323049832941699
0.4598750363011213
0.484475521678974
0.503073423975435
0.5161544267817576
0.5250750201500934
0.5310839951441775
0.5351148341549805
