In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [2]:
N=100
D=2

In [3]:
X=np.random.rand(N,D)
ones=np.array([[1]*N]).T

In [4]:
X

array([[6.62307726e-01, 6.84556624e-02],
       [6.56618314e-01, 8.25517947e-01],
       [5.31957344e-01, 1.07426479e-01],
       [8.56279889e-01, 2.05707437e-02],
       [5.02478606e-01, 1.41800597e-01],
       [4.15130855e-01, 8.16439955e-01],
       [4.94628524e-01, 1.27379224e-01],
       [7.45984515e-01, 6.93373590e-01],
       [7.26461212e-01, 2.25894343e-01],
       [2.53951476e-01, 5.40299297e-01],
       [7.35747675e-01, 2.45270934e-01],
       [9.83183387e-01, 6.92701101e-01],
       [2.75862316e-02, 4.07666738e-01],
       [7.17756158e-01, 1.74109555e-01],
       [8.62205945e-01, 6.23349884e-01],
       [2.95102169e-01, 8.59432525e-01],
       [4.33299653e-01, 8.88129031e-01],
       [9.90335205e-01, 1.48626746e-01],
       [3.98697657e-01, 4.32656673e-01],
       [3.32034979e-01, 7.95326976e-01],
       [2.75334545e-01, 5.21010477e-01],
       [9.64875456e-01, 6.31653111e-01],
       [3.66273363e-01, 2.42107522e-01],
       [9.64549263e-01, 6.27893345e-01],
       [3.658294

In [5]:
ones

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [8]:
s=np.concatenate((ones,X), axis=1)

In [9]:
s

array([[1.00000000e+00, 6.62307726e-01, 6.84556624e-02],
       [1.00000000e+00, 6.56618314e-01, 8.25517947e-01],
       [1.00000000e+00, 5.31957344e-01, 1.07426479e-01],
       [1.00000000e+00, 8.56279889e-01, 2.05707437e-02],
       [1.00000000e+00, 5.02478606e-01, 1.41800597e-01],
       [1.00000000e+00, 4.15130855e-01, 8.16439955e-01],
       [1.00000000e+00, 4.94628524e-01, 1.27379224e-01],
       [1.00000000e+00, 7.45984515e-01, 6.93373590e-01],
       [1.00000000e+00, 7.26461212e-01, 2.25894343e-01],
       [1.00000000e+00, 2.53951476e-01, 5.40299297e-01],
       [1.00000000e+00, 7.35747675e-01, 2.45270934e-01],
       [1.00000000e+00, 9.83183387e-01, 6.92701101e-01],
       [1.00000000e+00, 2.75862316e-02, 4.07666738e-01],
       [1.00000000e+00, 7.17756158e-01, 1.74109555e-01],
       [1.00000000e+00, 8.62205945e-01, 6.23349884e-01],
       [1.00000000e+00, 2.95102169e-01, 8.59432525e-01],
       [1.00000000e+00, 4.33299653e-01, 8.88129031e-01],
       [1.00000000e+00, 9.90335

In [10]:
w=np.random.rand(D+1)
w

array([0.69870667, 0.7397794 , 0.4133839 ])

In [11]:
Y=np.dot(s,w)
Y

array([1.21696675, 1.5257152 , 1.13664613, 1.3406685 , 1.12904807,
       1.34331505, 1.11727918, 1.53720012, 1.32950879, 1.10992577,
       1.34438869, 1.71239696, 0.88763726, 1.30166197, 1.59423167,
       1.27229274, 1.38639107, 1.49277615, 1.17250828, 1.27311467,
       1.11777083, 1.67361688, 1.06975151, 1.67182134, 1.19289916,
       0.76898908, 1.48763859, 1.05667016, 0.9490273 , 0.8994722 ,
       1.00664191, 1.12701322, 1.53876278, 1.29712731, 1.17788827,
       1.21780436, 1.241807  , 1.01812439, 1.46183539, 1.25957352,
       1.27244614, 1.32828094, 1.11243058, 1.38982746, 1.37600117,
       1.42585143, 1.28563437, 1.64191214, 1.03333643, 1.02951131,
       1.2321614 , 0.98741502, 1.6730558 , 1.12709513, 1.15420157,
       1.58942788, 0.89435693, 0.94460965, 1.13261909, 0.94964388,
       0.91480404, 1.76108275, 1.36246067, 1.47972114, 1.21320608,
       1.61825232, 1.4798555 , 1.41736627, 1.46267188, 1.52875654,
       0.88690294, 1.12773523, 1.15638616, 1.68813716, 0.99413

In [17]:
sigmoid = 1/1+np.exp(-Y)

In [18]:
print(sigmoid)

[1.29612703 1.21746547 1.32089345 1.26167068 1.32334091 1.26097907
 1.32716875 1.21498218 1.26460721 1.32958343 1.26069903 1.18043278
 1.41162717 1.27207923 1.20306449 1.28018848 1.24997582 1.22474785
 1.30958943 1.27995828 1.32700794 1.18756743 1.34309376 1.18790452
 1.30334055 1.46348138 1.22590548 1.34761138 1.38711739 1.4067843
 1.36544412 1.32399953 1.2146465  1.27331582 1.30792831 1.2958791
 1.28886177 1.36127191 1.23181042 1.28377502 1.28014551 1.2649323
 1.32875892 1.24911828 1.25258659 1.24030377 1.27647514 1.19360948
 1.35581782 1.35718147 1.2916615  1.37253845 1.1876727  1.32397299
 1.31530919 1.20404231 1.40887045 1.38883132 1.32218831 1.38687877
 1.40059512 1.17185868 1.25603    1.22770118 1.29724277 1.19824487
 1.22767059 1.24235146 1.2316166  1.21680509 1.41192955 1.32376568
 1.31462112 1.18486358 1.37004322 1.24092757 1.22345297 1.30559901
 1.36726856 1.25744961 1.38608756 1.27852517 1.29775195 1.27924712
 1.3316334  1.17714009 1.33392464 1.29417507 1.3941103  1.2111272