In [3]:
import numpy as np

In [4]:
a = np.random.randn(5)
a

array([-2.80083498,  0.16339218, -0.6408753 ,  0.93059476, -1.33451065])

In [5]:
exp =np.exp(a)
exp

array([0.06075931, 1.1774984 , 0.52683109, 2.53601704, 0.26328698])

In [6]:
ans = exp/exp.sum()

In [7]:
ans

array([0.01331159, 0.25797482, 0.11542194, 0.55560885, 0.05768281])

In [8]:
ans.sum()

1.0

In [9]:
A = np.random.randn(100, 5)
A

array([[ 1.27954844e+00,  7.08225201e-01,  2.02800264e-01,
        -4.90487030e-01,  3.73158065e-01],
       [-4.95488653e-01,  6.62122344e-02, -1.44261289e+00,
         3.95781436e-01,  7.48515810e-01],
       [ 1.60004867e+00, -1.06869156e-02, -1.39076814e+00,
         2.36386498e-02,  6.81074680e-02],
       [-5.95320068e-01,  1.00933560e-02,  1.04063893e+00,
        -7.84490389e-01,  7.71673769e-01],
       [-2.05126579e+00, -1.91927321e+00,  1.37174114e+00,
         1.84538688e+00,  2.92602423e-01],
       [-7.99537865e-01,  1.88086709e+00, -1.22384687e+00,
        -8.25948209e-01,  2.35897586e-01],
       [ 1.13819866e+00,  9.49103762e-01,  1.02531796e+00,
         5.06309197e-01,  1.08936649e+00],
       [ 1.28100387e-01, -6.07148283e-01, -1.06582347e+00,
        -9.37243510e-01,  1.07465552e+00],
       [-1.03289024e-01, -5.61181092e-01, -1.04338795e-01,
        -7.08807013e-01,  3.97088842e-01],
       [-5.53370578e-01, -2.08443436e-01,  2.36639160e-01,
        -1.56861956e-01

In [10]:
exp = np.exp(A)
exp

array([[ 3.595016  ,  2.03038453,  1.2248278 ,  0.6123281 ,  1.45231388],
       [ 0.60927311,  1.06845346,  0.2363095 ,  1.48554459,  2.11386032],
       [ 4.9532735 ,  0.98936999,  0.24888405,  1.02392026,  1.07048034],
       [ 0.55138606,  1.01014447,  2.83102527,  0.4563522 ,  2.16338423],
       [ 0.12857206,  0.14671355,  3.94220866,  6.33054846,  1.33990997],
       [ 0.44953666,  6.55918982,  0.29409664,  0.43781965,  1.26604464],
       [ 3.12114106,  2.58339329,  2.7879818 ,  1.65915626,  2.97239045],
       [ 1.1366671 ,  0.54490256,  0.3444441 ,  0.39170608,  2.92898375],
       [ 0.90186627,  0.57053481,  0.90092002,  0.49223107,  1.48748808],
       [ 0.57500843,  0.81184696,  1.26698386,  0.85482205,  0.27297493],
       [ 2.33132637,  1.02192449,  0.26082307,  1.33616891,  1.47900452],
       [ 0.83158733,  0.96246317,  1.1233357 ,  1.16070853,  0.68125075],
       [ 2.11316882,  0.70095617,  4.11938296,  1.5664552 ,  1.58689204],
       [ 0.2855588 ,  1.79941708,  0.0

In [11]:
answer = exp/exp.sum()
answer

array([[4.11848846e-03, 2.32603006e-03, 1.40317572e-03, 7.01489565e-04,
        1.66378619e-03],
       [6.97989738e-04, 1.22403161e-03, 2.70718671e-04, 1.70185564e-03,
        2.42166080e-03],
       [5.67452266e-03, 1.13343275e-03, 2.85124211e-04, 1.17301391e-03,
        1.22635364e-03],
       [6.31673714e-04, 1.15723221e-03, 3.24325258e-03, 5.22801926e-04,
        2.47839592e-03],
       [1.47293510e-04, 1.68076603e-04, 4.51623605e-03, 7.25234345e-03,
        1.53501507e-03],
       [5.14993969e-04, 7.51427743e-03, 3.36920225e-04, 5.01570836e-04,
        1.45039417e-03],
       [3.57561231e-03, 2.95956275e-03, 3.19394152e-03, 1.90074701e-03,
        3.40520203e-03],
       [1.30217789e-03, 6.24246156e-04, 3.94598814e-04, 4.48742642e-04,
        3.35547485e-03],
       [1.03318757e-03, 6.53610732e-04, 1.03210353e-03, 5.63905138e-04,
        1.70408212e-03],
       [6.58735756e-04, 9.30060482e-04, 1.45147014e-03, 9.79293211e-04,
        3.12722979e-04],
       [2.67079221e-03, 1.1707

In [12]:
answer.sum()

1.0

In [13]:
answer = exp/exp.sum(axis = 1,keepdims = True)
answer

array([[0.40326061, 0.22775256, 0.13739154, 0.06868615, 0.16290914],
       [0.11050687, 0.19379068, 0.04286062, 0.26944055, 0.38340128],
       [0.59779344, 0.11940364, 0.03003696, 0.12357339, 0.12919257],
       [0.07863136, 0.14405339, 0.40372323, 0.06507889, 0.30851313],
       [0.01081532, 0.01234136, 0.33161376, 0.53251797, 0.11271158],
       [0.04991143, 0.72825774, 0.03265314, 0.04861051, 0.14056718],
       [0.2378182 , 0.19684402, 0.21243283, 0.12642093, 0.22648402],
       [0.21259213, 0.10191374, 0.06442177, 0.07326123, 0.54781113],
       [0.20718078, 0.13106582, 0.2069634 , 0.11307754, 0.34171246],
       [0.15205281, 0.2146814 , 0.33503589, 0.22604555, 0.07218434],
       [0.36261264, 0.15894932, 0.04056821, 0.20782664, 0.23004318],
       [0.17472725, 0.20222595, 0.23602735, 0.24387986, 0.14313959],
       [0.20949729, 0.06949204, 0.40839121, 0.15529669, 0.15732277],
       [0.05679901, 0.35791268, 0.01514915, 0.20483019, 0.36530897],
       [0.05803923, 0.72027624, 0.

In [14]:
answer.sum(axis = 1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
exp.sum(axis = 1, keepdims = True) #convert 2d dimensional array by using keepdims

array([[ 8.91487032],
       [ 5.51344098],
       [ 8.28592815],
       [ 7.01229223],
       [11.88795269],
       [ 9.00668741],
       [13.12406286],
       [ 5.3467036 ],
       [ 4.35304025],
       [ 3.78163623],
       [ 6.42924736],
       [ 4.75934548],
       [10.08685519],
       [ 5.02753099],
       [ 5.40311208],
       [ 4.17027326],
       [30.46629345],
       [10.68339821],
       [ 8.8655143 ],
       [13.75227221],
       [ 6.42299048],
       [ 8.22759029],
       [16.23285832],
       [ 3.91692965],
       [ 2.97181314],
       [ 3.66151113],
       [ 3.53036659],
       [ 2.87511447],
       [12.18255728],
       [10.87703795],
       [ 7.08552976],
       [20.69566292],
       [ 6.52621485],
       [11.56338697],
       [11.26767845],
       [ 4.25183285],
       [23.94225231],
       [ 9.2381051 ],
       [ 7.08458919],
       [ 5.75889226],
       [ 7.11515865],
       [ 7.22537492],
       [17.17904075],
       [ 9.93050605],
       [ 4.66851292],
       [ 6

In [16]:
exp.sum(axis = 1, keepdims = True).shape #shape of the matrix

(100, 1)